   - name: Get latest url for linux-amd64 release for aws-iam-authenticator
     uri:
       url: https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/latest
       return_content: true
       body_format: json
     register: json_response

   - name: Download and install aws-iam-authenticator
     get_url:
       url:  " {{ json_response.json | to_json | from_json| json_query(\"assets[?ends_with(name,'linux_amd64')].browser_download_url | [0]\") }}"
       mode: 555
       dest: /usr/local/bin/aws-iam-authenticator
