---
- name: Download kubectl binary
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    checksum: "{{ kubectl_checksum_binary }}"
    dest: "/tmp"
  tags:
    - kubectl

- name: Copy kubectl binary to destination directory
  copy:
    src: "/tmp/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: "0755"
    owner: "root"
    group: "root"
    remote_src: yes
